---
title: "A4: Incarceration"
output: html_document
---

### Introduction

For many decades, the United States has faced increasing amounts of disparities regarding the racial demographics in jails and prisons. Stricter government policies along with increased police presence in certain regions has led to the mass incarceration of Black, Latinx, APPI, etc. people. While this affects the demographics of jails and prisons, it also affects American society. This can influence what neighborhoods are policed more often and even who is targeted by the police. To better understand this issue, I will be observing and analyzing data sets to compare the total prison populations between White and Black Americans, as well as their difference in mean prison population per 100,000 people in various counties. These factors will also be compared over time, from 1990-2010.

### Summary Information

When investigating these data sets, the first value I wanted to find was the difference between the total White prison population and total Black prison population in 2010. This would give us the broadest overview of any racial disparities in the total prison population. The prison population of White Americans was **448,158** and for Black Americans it was **488,969**. This tells us that there is are **40,811** more Black Americans in prison than White Americans. While this gives us an idea of some sort of difference in the total prison population, the prison population *rate* is more telling of racial disparities due to differences in racial populations in the United States. I chose to find values that would compare the mean prison rate per 100,000 people across all counties between White and Black Americans, and then I chose to compare those numbers from 1990 to 2010. In 1990 White Americans had an average of **249.42** people in prison per 100,000 people, while Black Americans had an average of **2028.65** people in prison per 100,000 people. Immediately you can notice there is a large gap between the two groups. Jumping forward, I also calculated those statistics 20 years later in 2010. White Americans had a rate of **528.76**, while Black Americans had a rate of **3237.458**. This shows that even 2 decades later, the disparity still remains. 

### The Dataset

The data used in this report was collected by the **Vera Institute**. According to their website, they do research and collect this data by working alongside community members and local organizations and government. They say that their mission is to is to end the overcriminalization and mass incarceration of people of color, immigrants, and people experiencing poverty. They do this work in order to develop an idea for how to disrupt the incarceration system and its devastating impacts. In the prison population and rate datasets there are **153,811 observations**. The total prison population dataset has **36 features** and the prison population rate dataset has **23 features**. Because this dataset deals with large numbers and widespread information regarding a historically systematic topic like race, there are some questions of power that need to be considered. For example, it is important to consider the identities of the individuals who collected this data as their own personal perspectives could affect what they did/didn't include. Additionally, one may want to consider who has control over this data and what may have been withheld or not reported as this can influence the accuracy of the reflections of the populations we are observing. This connects to limitations the data may have, including the many cells of unreported or "NA" data. This can cause issues with data accuracy and drawing valid conclusions from the data.

### Trends Over Time Chart

Include a chart. Make sure to describe why you included the chart, and what patterns emerged

The first chart that you will create and include will show the trend over time of your variable/topic. Think carefully about what you want to communicate to your user (you may have to find relevant trends in the dataset first!). Here are some requirements to help guide your design:

- Show more than one, but fewer than ~10 trends
  - This may mean showing the same measure for different locations or different racial groups. Think carefully about a meaningful comparison of locations (e.g., the top 10 counties in a state, top 10 states, etc.)
- You must have clear x and y axis labels
- The chart needs a clear title 
- You need a legend for your different line colors and a clear legend title

When we say "clear" or "human readable" titles and labels, that means that you should not just display the variable name.

Here's an example of how to run an R script inside an RMarkdown file:

```{r, echo = FALSE, code = readLines("chart1_example.R")}
```

### Variable Comparison Chart

Include a chart. Make sure to describe why you included the chart, and what patterns emerged

The second chart that you will create and include will show how two different (continuous) variables are related to one another. Again, think carefully about what such a comparison means and what you want to communicate to your user (you may have to find relevant trends in the dataset first!). Here are some requirements to help guide your design:

- You must have clear x and y axis labels
- The chart needs a clear title 
- If you choose to add a color encoding (not required), you need a legend for your different color and a clear legend title

### Map

Include a chart. Make sure to describe why you included the chart, and what patterns emerged

The last chart that you will create and include will show how a variable is distributed geographically. Again, think carefully about what such a comparison means and what you want to communicate to your user (you may have to find relevant trends in the dataset first!). Here are some requirements to help guide your design:

- Your map needs a title
- Your color scale needs a legend with a clear label
- Use a map based coordinate system to set the aspect ratio of your map

